version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}   # Passe DATABASE_URL du .env
    env_file:
      - ./.env
    ports:
      - "3000:3000"   # API backend
      - "5555:5555"   # Prisma Studio
    volumes:
      - ./backend:/usr/src/app       # Live reload pour dev
      - /usr/src/app/node_modules    # Ã‰vite conflits node_modules
    depends_on:
      - database
    command: npm run start:dev      # Dev mode. Pour prod : start:prod

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: leamyriamachaibou
      POSTGRES_PASSWORD: Sjkydby9mnxw
      POSTGRES_DB: ProjetApi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
